# Generated by Django 4.1.7 on 2023-12-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'codigo',
                'verbose_name_plural': 'Codigos financieros',
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'destino',
                'verbose_name_plural': 'Destinos',
            },
        ),
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_programatica', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'equivalencia',
                'verbose_name_plural': 'Equivalencias',
            },
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('clasificacion', models.CharField(blank=True, choices=[('LIBRE DISPONIBILIDAD', 'LIBRE DISPONIBILIDAD'), ('AFECTADO', 'AFECTADO')], default='LIBRE DISPONIBILIDAD', max_length=20, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
            options={
                'verbose_name': 'fondo',
                'verbose_name_plural': 'Fondos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=0)),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('cuit', models.CharField(blank=True, max_length=255, null=True)),
                ('ramo', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Agrupamiento')),
                ('nombre', models.CharField(max_length=2550, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('comprobante_operacion', models.CharField(blank=True, max_length=255, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.CreateModel(
            name='FondoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.fondo')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.recurso')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'Asignacion de Recursos',
            },
        ),
        migrations.CreateModel(
            name='FondoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.destino')),
                ('fondo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.fondo')),
            ],
            options={
                'verbose_name': 'destino',
                'verbose_name_plural': 'Asignacion de Destinos',
            },
        ),
        migrations.CreateModel(
            name='CodigoFinancieroFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.codigofinanciero')),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.fondo')),
            ],
            options={
                'verbose_name': 'fondo',
                'verbose_name_plural': 'Asignacion de Fondos',
            },
        ),
        migrations.AddField(
            model_name='codigofinanciero',
            name='fondo_afectado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.fondo'),
        ),
    ]
