# Generated by Django 4.1.7 on 2023-12-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigofinanciero',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
