# Generated by Django 4.1.7 on 2023-12-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_codigofinanciero_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='agrupamiento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Agrupamiento'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='nombre',
            field=models.CharField(max_length=2550, null=True, verbose_name='Descripcion'),
        ),
    ]
