# Generated by Django 4.2.5 on 2023-12-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_remove_destino_titulo_remove_recurso_agrupamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='tipo',
            new_name='numero',
        ),
    ]
