# Generated by Django 4.2.5 on 2023-12-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_expedientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sector',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
